### ISSUE TITLE
Using the wrong action hook

### ISSUE THREAD

**Issue by thesteve0** [logentries/le_openshift#9]
If I stop the app using any command. And then start the app again using:

rhc app start -a {appname}

The monitor daemon never starts because the deploy action_hook is never called. I think you need to actually use the post_start action hook. I can explain more if you need help with it

**Comment by andrea-sdl** [comment]
That's partly true.
The post_deploy isn't get called, therefore it doesn't pick up new logs (if present). 
The downside of using the post_start action hook is that it gets called for each cartridge, thus leading to duplicated lines in the tracking.
I'm working on a quick fix on my personal repo, once it's ready I'll try to do a pull request here so people can continue using logentries with openshift
